import React from 'react';
import {
	AbsoluteFill,
	Composition,
	Img,
	interpolate,
	spring,
	useCurrentFrame,
	useVideoConfig,
} from 'remotion';

type StatTone = 'blurple' | 'green' | 'pink';

type HeadlineStat = {
	label: string;
	value: string;
	tone: StatTone;
};

type BreakdownStat = {
	label: string;
	value: number;
};

type TopSound = {
	name: string;
	plays: number;
};

type WeeklyItem = {
	name: string;
	value: string;
	meta?: string;
};

type WeeklySection = {
	title: string;
	subtitle?: string;
	items: WeeklyItem[];
};

export type YearReviewProps = {
	username: string;
	displayName: string;
	year: number;
	mode?: 'year' | 'weekly';
	commandLabel?: string;
	kicker?: string;
	title?: string;
	subtitle?: string;
	avatarUrl?: string | null;
	headlineStats: HeadlineStat[];
	playBreakdown: BreakdownStat[];
	rankText: string;
	topSounds: TopSound[];
	timing: {
		favoriteDay: string;
		peakHour: string;
		activeDays: string;
		longestStreak: string;
	};
	journey: {
		firstSound: string;
		firstDate: string;
		latestSound: string;
		latestDate: string;
	};
	finalLine: string;
	outroTitle?: string;
	footerAccent?: string;
	weeklyWindow?: string;
	weeklySections?: WeeklySection[];
};

const defaultProps: YearReviewProps = {
	username: 'sopustos',
	displayName: 'sopustos',
	year: 2026,
	mode: 'year',
	commandLabel: '/yearreview',
	kicker: '2026 voice-channel cinema',
	title: "sopustos's year review",
	subtitle: 'the soundboard recap nobody asked for but everyone deserves',
	avatarUrl: null,
	headlineStats: [
		{label: 'plays', value: '420', tone: 'blurple'},
		{label: 'unique sounds', value: '69', tone: 'green'},
		{label: 'voice hours', value: '37h', tone: 'pink'},
	],
	playBreakdown: [
		{label: 'requested', value: 320},
		{label: 'random', value: 80},
		{label: 'favorites', value: 20},
	],
	rankText: 'Rank #1 of 8',
	topSounds: [
		{name: 'gompreview', plays: 42},
		{name: 'killsoundpreview', plays: 31},
		{name: 'hello trailer', plays: 18},
	],
	timing: {
		favoriteDay: 'Friday',
		peakHour: '23:00',
		activeDays: '44',
		longestStreak: '6 days',
	},
	journey: {
		firstSound: 'gompreview',
		firstDate: '2026-01-03',
		latestSound: 'killsoundpreview',
		latestDate: '2026-12-29',
	},
	finalLine: '420 plays, 69 unique sounds, 37h in voice',
	outroTitle: 'See you in voice.',
	footerAccent: 'generated by /yearreview',
};

const colors: Record<StatTone, string> = {
	blurple: '#5865f2',
	green: '#57f287',
	pink: '#eb459e',
};

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

const sceneTimings = {
	intro: {start: 0, duration: 170},
	breakdown: {start: 170, duration: 150},
	topSounds: {start: 320, duration: 210},
	timing: {start: 530, duration: 160},
	journey: {start: 690, duration: 160},
	outro: {start: 850, duration: 170},
};

const weeklySceneTimings = [
	{start: 0, duration: 150},
	{start: 150, duration: 170},
	{start: 320, duration: 170},
	{start: 490, duration: 170},
	{start: 660, duration: 170},
	{start: 830, duration: 190},
];

const useSceneProgress = (start: number, duration: number) => {
	const frame = useCurrentFrame();
	const {fps} = useVideoConfig();
	const localFrame = frame - start;
	const entrance = spring({
		frame: localFrame,
		fps,
		config: {
			damping: 16,
			stiffness: 110,
			mass: 0.9,
		},
	});
	const exit = interpolate(localFrame, [duration - 24, duration], [1, 0], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	});
	const active = localFrame >= 0 && localFrame < duration;
	return {
		active,
		opacity: active ? entrance * exit : 0,
		y: interpolate(entrance, [0, 1], [30, 0]),
		localFrame,
	};
};

const Shell: React.FC<{children: React.ReactNode; scene: string; commandLabel?: string}> = ({children, scene, commandLabel}) => {
	return (
		<AbsoluteFill style={styles.stage}>
			<div style={styles.shell}>
				<div style={styles.topRail}>
					<div style={styles.brandPill}>DISCORD BRAIN ROT</div>
				<div style={styles.commandPill}>{commandLabel || '/yearreview'}</div>
			</div>
			<div style={styles.sceneTag}>{scene}</div>
			{children}
			</div>
		</AbsoluteFill>
	);
};

const Avatar: React.FC<{url?: string | null; name: string}> = ({url, name}) => {
	return (
		<div style={styles.avatarWrap}>
			{url ? <Img src={url} style={styles.avatar} /> : <div style={styles.avatarFallback}>{name.slice(0, 1).toUpperCase()}</div>}
		</div>
	);
};

const MetricCard: React.FC<{stat: HeadlineStat; delay: number}> = ({stat, delay}) => {
	const frame = useCurrentFrame();
	const {fps} = useVideoConfig();
	const pop = spring({frame: frame - delay, fps, config: {damping: 12, stiffness: 130}});
	return (
		<div
			style={{
				...styles.metricCard,
				borderColor: colors[stat.tone],
				transform: `translateY(${(1 - pop) * 24}px) scale(${0.92 + pop * 0.08})`,
				opacity: pop,
			}}
		>
			<div style={{...styles.metricGlow, background: colors[stat.tone]}} />
			<div style={styles.metricValue}>{stat.value}</div>
			<div style={styles.metricLabel}>{stat.label}</div>
		</div>
	);
};

const IntroScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.intro.start, sceneTimings.intro.duration);
	if (!progress.active) return null;
	return (
		<Shell scene="wrapped.exe" commandLabel={data.commandLabel}>
			<div style={{...styles.weeklyScene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.heroRow}>
					<Avatar url={data.avatarUrl} name={data.displayName} />
					<div>
						<div style={styles.kicker}>{data.kicker || `${data.year} voice-channel cinema`}</div>
						<div style={styles.heroTitle}>{data.title || `${data.displayName}'s year review`}</div>
						<div style={styles.heroSub}>{data.subtitle || 'the soundboard recap nobody asked for but everyone deserves'}</div>
					</div>
				</div>
				<div style={styles.introMetricGrid}>
					{data.headlineStats.map((stat, index) => (
						<MetricCard key={stat.label} stat={stat} delay={18 + index * 6} />
					))}
				</div>
			</div>
		</Shell>
	);
};

const WeeklyIntroScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const timing = weeklySceneTimings[0];
	const progress = useSceneProgress(timing.start, timing.duration);
	if (!progress.active) return null;
	return (
		<Shell scene="weekly digest" commandLabel={data.commandLabel}>
			<div style={{...styles.weeklyScene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.weeklyHeroTitle}>{data.title || `${data.displayName} weekly wrapped`}</div>
				<div style={styles.weeklyWindow}>{data.weeklyWindow || data.rankText}</div>
				<div style={styles.weeklyMetricGrid}>
					{data.headlineStats.map((stat, index) => (
						<MetricCard key={stat.label} stat={stat} delay={18 + index * 6} />
					))}
				</div>
			</div>
		</Shell>
	);
};

const WeeklyListScene: React.FC<{data: YearReviewProps; section: WeeklySection; index: number}> = ({data, section, index}) => {
	const timing = weeklySceneTimings[index + 1];
	const progress = useSceneProgress(timing.start, timing.duration);
	if (!progress.active) return null;
	return (
		<Shell scene={section.subtitle || 'weekly stats'} commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.sectionTitle}>{section.title}</div>
				{section.subtitle ? <div style={styles.sectionSub}>{section.subtitle}</div> : null}
				<div style={styles.weeklyList}>
					{section.items.slice(0, 5).map((item, itemIndex) => {
						const reveal = spring({
							frame: progress.localFrame - 12 - itemIndex * 4,
							fps: 30,
							config: {damping: 14, stiffness: 120},
						});
						return (
							<div
								key={`${section.title}-${item.name}-${itemIndex}`}
								style={{
									...styles.weeklyRow,
									opacity: reveal,
									transform: `translateX(${(1 - reveal) * -34}px)`,
								}}
							>
								<div style={styles.weeklyRank}>{itemIndex + 1}</div>
								<div style={styles.weeklyItemBody}>
									<div style={styles.weeklyItemName}>{item.name}</div>
									{item.meta ? <div style={styles.weeklyItemMeta}>{item.meta}</div> : null}
								</div>
								<div style={styles.weeklyItemValue}>{item.value}</div>
							</div>
						);
					})}
				</div>
			</div>
		</Shell>
	);
};

const WeeklyWrapped: React.FC<YearReviewProps> = (data) => {
	const sections = data.weeklySections || [];
	return (
		<AbsoluteFill>
			<WeeklyIntroScene data={data} />
			{sections.slice(0, 5).map((section, index) => (
				<WeeklyListScene key={section.title} data={data} section={section} index={index} />
			))}
		</AbsoluteFill>
	);
};

const BreakdownScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.breakdown.start, sceneTimings.breakdown.duration);
	if (!progress.active) return null;
	const maxValue = Math.max(1, ...data.playBreakdown.map((item) => item.value));
	return (
		<Shell scene="damage report" commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.sectionTitle}>How the button got abused</div>
				<div style={styles.sectionSub}>{data.rankText}</div>
				<div style={styles.breakdownWrap}>
					{data.playBreakdown.map((item, index) => {
						const width = interpolate(progress.localFrame, [18 + index * 8, 48 + index * 8], [0, item.value / maxValue], {
							extrapolateLeft: 'clamp',
							extrapolateRight: 'clamp',
						});
						return (
							<div key={item.label} style={styles.breakdownRow}>
								<div style={styles.breakdownLabel}>{item.label}</div>
								<div style={styles.breakdownTrack}>
									<div style={{...styles.breakdownBar, width: `${clamp(width * 100, 3, 100)}%`}} />
								</div>
								<div style={styles.breakdownValue}>{item.value}</div>
							</div>
						);
					})}
				</div>
			</div>
		</Shell>
	);
};

const TopSoundsScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.topSounds.start, sceneTimings.topSounds.duration);
	if (!progress.active) return null;
	const maxCount = Math.max(1, ...data.topSounds.map((sound) => sound.plays));
	const sounds = data.topSounds.length ? data.topSounds.slice(0, 4) : [{name: 'No sounds played yet', plays: 0}];
	return (
		<Shell scene="hall of fame" commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.sectionTitle}>Top sounds</div>
				<div style={styles.sectionSub}>the clips that kept crawling back into chat</div>
				<div style={styles.soundList}>
					{sounds.map((sound, index) => {
						const reveal = spring({
							frame: progress.localFrame - 16 - index * 7,
							fps: 30,
							config: {damping: 14, stiffness: 120},
						});
						return (
							<div
								key={`${sound.name}-${index}`}
								style={{
									...styles.soundRow,
									opacity: reveal,
									transform: `translateX(${(1 - reveal) * -42}px)`,
								}}
							>
								<div style={styles.soundRank}>{index + 1}</div>
								<div style={styles.soundBody}>
									<div style={styles.soundName}>{sound.name}</div>
									<div style={styles.soundTrack}>
										<div style={{...styles.soundBar, width: `${Math.max(8, (sound.plays / maxCount) * 100)}%`}} />
									</div>
								</div>
								<div style={styles.soundPlays}>{sound.plays}x</div>
							</div>
						);
					})}
				</div>
			</div>
		</Shell>
	);
};

const TimingScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.timing.start, sceneTimings.timing.duration);
	if (!progress.active) return null;
	const facts = [
		['favorite day', data.timing.favoriteDay],
		['peak hour', data.timing.peakHour],
		['active days', data.timing.activeDays],
		['longest streak', data.timing.longestStreak],
	];
	return (
		<Shell scene="activity radar" commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.sectionTitle}>When the chaos peaked</div>
				<div style={styles.factGrid}>
					{facts.map(([label, value], index) => (
						<div key={label} style={{...styles.factCard, transform: `rotate(${index % 2 === 0 ? -1 : 1}deg)`}}>
							<div style={styles.factLabel}>{label}</div>
							<div style={styles.factValue}>{value}</div>
						</div>
					))}
				</div>
			</div>
		</Shell>
	);
};

const JourneyScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.journey.start, sceneTimings.journey.duration);
	if (!progress.active) return null;
	return (
		<Shell scene="lore archive" commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.sectionTitle}>First and latest</div>
				<div style={styles.journeyGrid}>
					<div style={styles.journeyCard}>
						<div style={styles.factLabel}>first sound</div>
						<div style={styles.journeyName}>{data.journey.firstSound}</div>
						<div style={styles.dateText}>{data.journey.firstDate}</div>
					</div>
					<div style={styles.journeyArrow}>→</div>
					<div style={styles.journeyCard}>
						<div style={styles.factLabel}>latest sound</div>
						<div style={styles.journeyName}>{data.journey.latestSound}</div>
						<div style={styles.dateText}>{data.journey.latestDate}</div>
					</div>
				</div>
			</div>
		</Shell>
	);
};

const OutroScene: React.FC<{data: YearReviewProps}> = ({data}) => {
	const progress = useSceneProgress(sceneTimings.outro.start, sceneTimings.outro.duration);
	if (!progress.active) return null;
	return (
		<Shell scene="final boss card" commandLabel={data.commandLabel}>
			<div style={{...styles.scene, opacity: progress.opacity, transform: `translateY(${progress.y}px)`}}>
				<div style={styles.outroTitle}>{data.outroTitle || 'See you in voice.'}</div>
				<div style={styles.outroSub}>{data.finalLine}</div>
				<div style={styles.footerCard}>
					<span style={styles.footerAccent}>{data.footerAccent || `generated by ${data.commandLabel || '/yearreview'}`}</span>
					<span>Discord Brain Rot</span>
				</div>
			</div>
		</Shell>
	);
};

const YearReview: React.FC<YearReviewProps> = (data) => {
	if (data.mode === 'weekly') {
		return <WeeklyWrapped {...data} />;
	}
	return (
		<AbsoluteFill>
			<IntroScene data={data} />
			<BreakdownScene data={data} />
			<TopSoundsScene data={data} />
			<TimingScene data={data} />
			<JourneyScene data={data} />
			<OutroScene data={data} />
		</AbsoluteFill>
	);
};

export const YearReviewRoot: React.FC = () => {
	return (
		<Composition
			id="YearReview"
			component={YearReview}
			durationInFrames={1020}
			fps={30}
			width={960}
			height={540}
			defaultProps={defaultProps}
		/>
	);
};

const fontStack = 'Inter, "DejaVu Sans", "Noto Color Emoji", Arial, sans-serif';

const styles: Record<string, React.CSSProperties> = {
	stage: {
		background: '#313338',
		color: 'white',
		fontFamily: fontStack,
		overflow: 'hidden',
	},
	shell: {
		position: 'absolute',
		inset: 0,
		border: '0 solid transparent',
		borderRadius: 0,
		background: '#313338',
		boxShadow: 'none',
		overflow: 'hidden',
	},
	topRail: {
		position: 'absolute',
		top: 24,
		left: 28,
		right: 28,
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	brandPill: {
		padding: '10px 14px',
		borderRadius: 10,
		background: 'rgba(87,242,135,0.14)',
		color: '#57f287',
		fontSize: 18,
		fontWeight: 900,
		letterSpacing: 0,
	},
	commandPill: {
		padding: '10px 18px',
		borderRadius: 14,
		background: '#5865f2',
		fontSize: 20,
		fontWeight: 900,
	},
	sceneTag: {
		position: 'absolute',
		right: 34,
		top: 78,
		color: '#72767d',
		fontSize: 15,
		fontWeight: 800,
		textTransform: 'uppercase',
		opacity: 0.72,
	},
	scene: {
		position: 'absolute',
		inset: '106px 44px 48px 44px',
	},
	weeklyScene: {
		position: 'absolute',
		inset: '96px 44px 30px 44px',
	},
	heroRow: {
		display: 'flex',
		alignItems: 'center',
		gap: 22,
	},
	avatarWrap: {
		width: 94,
		height: 94,
		borderRadius: 28,
		padding: 5,
		background: 'linear-gradient(135deg, #5865f2, #eb459e, #57f287)',
		boxShadow: '0 18px 48px rgba(88,101,242,0.35)',
		flex: '0 0 auto',
	},
	avatar: {
		width: '100%',
		height: '100%',
		borderRadius: 23,
		objectFit: 'cover',
	},
	avatarFallback: {
		width: '100%',
		height: '100%',
		borderRadius: 23,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		background: '#23252d',
		fontSize: 48,
		fontWeight: 900,
	},
	kicker: {
		color: '#57f287',
		fontSize: 19,
		fontWeight: 900,
		textTransform: 'uppercase',
	},
	heroTitle: {
		fontSize: 48,
		fontWeight: 950,
		lineHeight: 1,
		marginTop: 5,
	},
	heroSub: {
		color: '#b9bbbe',
		fontSize: 20,
		marginTop: 8,
		fontWeight: 700,
		lineHeight: 1.12,
	},
	introMetricGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(3, 1fr)',
		gap: 16,
		marginTop: 26,
	},
	metricGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(3, 1fr)',
		gap: 20,
		marginTop: 42,
	},
	metricCard: {
		position: 'relative',
		minHeight: 92,
		borderRadius: 14,
		border: '2px solid',
		background: 'rgba(15,16,22,0.78)',
		padding: 16,
		overflow: 'hidden',
	},
	metricGlow: {
		position: 'absolute',
		right: -30,
		top: -30,
		width: 110,
		height: 110,
		borderRadius: 90,
		filter: 'blur(22px)',
		opacity: 0.46,
	},
	metricValue: {
		fontSize: 34,
		fontWeight: 950,
		lineHeight: 1,
		whiteSpace: 'nowrap',
	},
	metricLabel: {
		marginTop: 10,
		color: '#b9bbbe',
		fontSize: 14,
		fontWeight: 900,
		textTransform: 'uppercase',
	},
	weeklyHeroTitle: {
		fontSize: 54,
		fontWeight: 950,
		lineHeight: 1,
		maxWidth: 760,
	},
	weeklyWindow: {
		marginTop: 14,
		color: '#b9bbbe',
		fontSize: 22,
		fontWeight: 850,
	},
	weeklyMetricGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(3, 1fr)',
		gap: 16,
		marginTop: 36,
	},
	weeklyList: {
		marginTop: 18,
		display: 'flex',
		flexDirection: 'column',
		gap: 6,
	},
	weeklyRow: {
		display: 'grid',
		gridTemplateColumns: '38px 1fr 126px',
		alignItems: 'center',
		gap: 12,
		padding: '5px 11px',
		borderRadius: 12,
		background: 'rgba(255,255,255,0.075)',
		border: '1px solid rgba(255,255,255,0.08)',
	},
	weeklyRank: {
		width: 30,
		height: 30,
		borderRadius: 10,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		background: '#57f287',
		color: '#0f1016',
		fontSize: 18,
		fontWeight: 950,
	},
	weeklyItemBody: {
		minWidth: 0,
	},
	weeklyItemName: {
		fontSize: 20,
		fontWeight: 900,
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	weeklyItemMeta: {
		marginTop: 2,
		fontSize: 13,
		fontWeight: 800,
		color: '#b9bbbe',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	weeklyItemValue: {
		textAlign: 'right',
		fontSize: 19,
		fontWeight: 950,
		color: '#fee75c',
		whiteSpace: 'nowrap',
	},
	sectionTitle: {
		fontSize: 48,
		fontWeight: 950,
		lineHeight: 1,
	},
	sectionSub: {
		marginTop: 10,
		color: '#b9bbbe',
		fontSize: 20,
		fontWeight: 800,
	},
	breakdownWrap: {
		marginTop: 38,
		display: 'flex',
		flexDirection: 'column',
		gap: 22,
	},
	breakdownRow: {
		display: 'grid',
		gridTemplateColumns: '170px 1fr 90px',
		alignItems: 'center',
		gap: 18,
	},
	breakdownLabel: {
		fontSize: 24,
		fontWeight: 900,
		color: '#ffffff',
		textTransform: 'uppercase',
	},
	breakdownTrack: {
		height: 34,
		borderRadius: 20,
		background: 'rgba(255,255,255,0.08)',
		overflow: 'hidden',
	},
	breakdownBar: {
		height: '100%',
		borderRadius: 20,
		background: 'linear-gradient(90deg, #5865f2, #eb459e, #fee75c)',
	},
	breakdownValue: {
		textAlign: 'right',
		fontSize: 30,
		fontWeight: 950,
	},
	soundList: {
		marginTop: 20,
		display: 'flex',
		flexDirection: 'column',
		gap: 8,
	},
	soundRow: {
		display: 'grid',
		gridTemplateColumns: '46px 1fr 68px',
		alignItems: 'center',
		gap: 14,
		padding: '7px 12px',
		borderRadius: 14,
		background: 'rgba(255,255,255,0.075)',
		border: '1px solid rgba(255,255,255,0.08)',
	},
	soundRank: {
		width: 38,
		height: 38,
		borderRadius: 12,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		background: '#fee75c',
		color: '#0f1016',
		fontSize: 23,
		fontWeight: 950,
	},
	soundBody: {
		minWidth: 0,
	},
	soundName: {
		fontSize: 22,
		fontWeight: 900,
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	soundTrack: {
		height: 8,
		marginTop: 6,
		borderRadius: 8,
		background: 'rgba(255,255,255,0.08)',
		overflow: 'hidden',
	},
	soundBar: {
		height: '100%',
		borderRadius: 8,
		background: '#57f287',
	},
	soundPlays: {
		textAlign: 'right',
		fontSize: 22,
		fontWeight: 950,
		color: '#57f287',
	},
	factGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(2, 1fr)',
		gap: 18,
		marginTop: 34,
	},
	factCard: {
		minHeight: 108,
		borderRadius: 18,
		background: 'rgba(255,255,255,0.08)',
		border: '1px solid rgba(255,255,255,0.1)',
		padding: 20,
		boxShadow: '0 18px 50px rgba(0,0,0,0.25)',
	},
	factLabel: {
		fontSize: 18,
		fontWeight: 950,
		color: '#b9bbbe',
		textTransform: 'uppercase',
	},
	factValue: {
		marginTop: 12,
		fontSize: 38,
		fontWeight: 950,
	},
	journeyGrid: {
		display: 'grid',
		gridTemplateColumns: '1fr 80px 1fr',
		alignItems: 'center',
		gap: 20,
		marginTop: 48,
	},
	journeyCard: {
		minHeight: 164,
		borderRadius: 20,
		background: 'rgba(88,101,242,0.18)',
		border: '1px solid rgba(88,101,242,0.42)',
		padding: 22,
		overflow: 'hidden',
	},
	journeyName: {
		marginTop: 16,
		fontSize: 30,
		fontWeight: 950,
		lineHeight: 1.08,
		overflow: 'hidden',
		display: '-webkit-box',
		WebkitLineClamp: 2,
		WebkitBoxOrient: 'vertical',
	},
	journeyArrow: {
		textAlign: 'center',
		fontSize: 54,
		fontWeight: 950,
		color: '#57f287',
	},
	dateText: {
		marginTop: 14,
		fontSize: 22,
		fontWeight: 850,
		color: '#b9bbbe',
	},
	outroTitle: {
		marginTop: 54,
		fontSize: 78,
		fontWeight: 950,
		lineHeight: 1,
		color: '#57f287',
	},
	outroSub: {
		marginTop: 24,
		fontSize: 32,
		fontWeight: 850,
		color: '#ffffff',
	},
	footerCard: {
		marginTop: 52,
		display: 'inline-flex',
		gap: 20,
		padding: '18px 24px',
		borderRadius: 18,
		background: 'rgba(255,255,255,0.08)',
		fontSize: 22,
		fontWeight: 900,
	},
	footerAccent: {
		color: '#fee75c',
	},
};
