"""
UI subpackage - Discord UI components (buttons, views, modals).

This package contains all Discord UI components used by the bot,
including buttons, views, and modals for sound controls, user events,
and various interactive features.
"""

# Import all components from the unified components file
# This maintains backwards compatibility while allowing future splitting
from bot.ui.components import (
    # Buttons
    ReplayButton,
    STSButton,
    IsolateButton,
    FavoriteButton,
    BlacklistButton,
    ChangeSoundNameButton,
    DownloadSoundButton,
    UploadSoundButton,
    PlayRandomButton,
    PlayRandomFavoriteButton,
    ListFavoritesButton,
    ListBlacklistButton,
    SlapButton,
    PlaySlapButton,
    ListSoundsButton,
    SubwaySurfersButton,
    SliceAllButton,
    FamilyGuyButton,
    BrainRotButton,
    StatsButton,
    ListLastScrapedSoundsButton,
    MuteToggleButton,
    PlaySoundButton,
    AssignUserEventButton,
    PaginationButton,
    ListUserFavoritesButton,
    DeleteEventButton,
    EventPaginationButton,
    SoundListButton,
    SoundListItemButton,
    CreateListButton,
    AddToListButton,
    RemoveFromListButton,
    DeleteListButton,
    SoundListPaginationButton,
    # Views
    ControlsView,
    SoundView,
    EventView,
    PaginatedEventView,
    DownloadedSoundView,
    SoundBeingPlayedView,
    SoundBeingPlayedWithSuggestionsView,
    UserEventSelectView,
    UploadChoiceView,
    PaginatedFavoritesView,
    PaginatedSoundListView,
    UserSoundListsView,
    # Selects
    EventTypeSelect,
    UserSelect,
    SimilarSoundsSelect,
    LoadingSimilarSoundsSelect,
    AddToListSelect,
    # Modals
    UploadSoundModal,
    ChangeSoundNameModal,
    CreateListModalWithSoundAdd,
)

__all__ = [
    # Buttons
    'ReplayButton',
    'STSButton',
    'IsolateButton',
    'FavoriteButton',
    'BlacklistButton',
    'ChangeSoundNameButton',
    'DownloadSoundButton',
    'UploadSoundButton',
    'PlayRandomButton',
    'PlayRandomFavoriteButton',
    'ListFavoritesButton',
    'ListBlacklistButton',
    'SlapButton',
    'PlaySlapButton',
    'ListSoundsButton',
    'SubwaySurfersButton',
    'SliceAllButton',
    'FamilyGuyButton',
    'BrainRotButton',
    'StatsButton',
    'ListLastScrapedSoundsButton',
    'MuteToggleButton',
    'PlaySoundButton',
    'AssignUserEventButton',
    'PaginationButton',
    'ListUserFavoritesButton',
    'DeleteEventButton',
    'EventPaginationButton',
    'SoundListButton',
    'SoundListItemButton',
    'CreateListButton',
    'AddToListButton',
    'RemoveFromListButton',
    'DeleteListButton',
    'SoundListPaginationButton',
    # Views
    'ControlsView',
    'SoundView',
    'EventView',
    'PaginatedEventView',
    'DownloadedSoundView',
    'SoundBeingPlayedView',
    'SoundBeingPlayedWithSuggestionsView',
    'UserEventSelectView',
    'UploadChoiceView',
    'PaginatedFavoritesView',
    'PaginatedSoundListView',
    'UserSoundListsView',
    # Selects
    'EventTypeSelect',
    'UserSelect',
    'SimilarSoundsSelect',
    'LoadingSimilarSoundsSelect',
    'AddToListSelect',
    # Modals
    'UploadSoundModal',
    'ChangeSoundNameModal',
    'CreateListModalWithSoundAdd',
]
